# Generated by Django 2.2.6 on 2019-10-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=15, verbose_name='Ключ')),
                ('value', models.TextField(verbose_name='Значение')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Свойства компании',
                'verbose_name_plural': 'Свойства компании',
                'db_table': 'contact_property',
            },
        ),
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('system_name', models.CharField(max_length=20, unique=True, verbose_name='Системное имя')),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередь')),
            ],
            options={
                'verbose_name': 'Разделы',
                'verbose_name_plural': 'Разделы',
                'db_table': 'partition',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Partition')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
                'db_table': 'main_page',
            },
        ),
    ]
