# Generated by Django 2.2.6 on 2019-10-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Услуга')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('time', models.PositiveIntegerField(verbose_name='Время')),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Цены',
                'verbose_name_plural': 'Цены',
                'db_table': 'price',
            },
        ),
    ]
