# Generated by Django 2.2.6 on 2019-11-02 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название услуги')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'type_service',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('time', models.PositiveIntegerField(verbose_name='Время (мин)')),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сортировка')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.TypeService', verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'db_table': 'price',
            },
        ),
    ]
